# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17d78ef8d2636f8ee68b293a0c3152b580b9e409a51d821852574ddbcd60d544f83ef8a8cfbd0c7e1d249e5eebff008a8573a100691472f5b3bdcf5af6946c54

test:
  secret_key_base: 6c950049ce82a8587043c2a4be03582505006189675701261dd653162f5b288852779fa897ca416e1be6318fd7fd7565fe750c85ff91d5a5d1ccd6f674e8cf12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
